### PR TITLE
Environment var to conditionally send results to Dynamo DB

### LINKED ISSUE #58: Ability to disable sending data to backend for local dev
Put in a flag for whether or not to send data to dynamo, so we don't spam the backend when doing heavy UI development. Perhaps a dev environment variable that's false by default but can be manually switched

### PR DESCRIPTION
**Pull request by eemshi**
Closes https://github.com/codefordenver/expunge-colorado-screener/issues/58

### CODE REVIEW

**Review by kadrianne — APPROVED** [review]
Thanks, Michelle! Just curious, how did you set the deployed version to use the .env.production file? On that note, where is the .env.test used?
Anyway, looks good to me!

**Comment by eemshi** [comment]
> Thanks, Michelle! Just curious, how did you set the deployed version to use the .env.production file? On that note, where is the .env.test used?
> Anyway, looks good to me!

@kadrianne React takes care of it for us, which is awesome! As long as the variable starts with `REACT_APP_`, it is automatically mapped to the yarn/npm commands according to the env file names (files on the left have more priority than files on the right):

`yarn start`:  `.env.development.local`, `.env.local`, `.env.development`, `.env`
`yarn run build`:  `.env.production.local`, `.env.local`, `.env.production`, `.env`
`yarn test`:  `.env.test.local`, `.env.test`, `.env`

I kept it simple with just the default `.env` and specific ones for prod/test.

**Comment by eemshi** [comment]
Forgot to include, here are the docs https://create-react-app.dev/docs/adding-custom-environment-variables

**Comment by kadrianne** [comment]
Oh awesome!! Thanks so much for the explanation and docs!

**Pull request merged**
