### PR TITLE
Issue9/scaffold survey data obj

### LINKED ISSUE #9: Scaffold survey data object
Don't need to flesh out question 6 or 8 at this time

### PR DESCRIPTION
**Pull request by jdhern17**
i've made the update to help the first page chain a bit better but am noticing that if the user fills out the responses out of order (or in my case, purposely selecting a response to reveal other questions, then switching back a previous response to hide the revealed questions) then the visibleIf resolution can still be based on the response given to a now-hidden answer (thereby leading to questions that aren't necessary). we may want to move to one question per page to minimize the incidence of users changing answers, but the issue may persist if there's a Previous button available.

### CODE REVIEW

**Comment by eemshi** [comment]
@kadrianne and I will be pairing on a go back button so we should all chat! https://github.com/codefordenver/expunge-colorado-screener/issues/13

**Comment by LegatusNewt** [comment]
This is good for now. You can add function calls to the surveyJS "expressions". That would probably allow us to have more complex logic. Also there is an option to clear the results of invisible questions. 

https://surveyjs.io/Examples/Library?id=condition-customfunctions&platform=jQuery&theme=modern#content-js

https://surveyjs.io/Documentation/Library/?id=surveymodel#clearInvisibleValues

**Review by LegatusNewt — APPROVED** [review]
Already commented without reviewing like a dummy

**Comment by kadrianne** [comment]
@jdhern17 great work so far! I would agree that giving questions their own page would help the UX. Will play around with data and test a bit today!

**Pull request merged**
